# Generated by Django 4.0.6 on 2022-10-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
