# Generated by Django 4.0.6 on 2022-10-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
